### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nagaadeveloper** [whoisdon/donkeyguide#1]
Error: RangeError: Maximum call stack size exceeded
NodeJs Version:  v20.9.0

Problema localizado na src/Structure/SlashCommands.js
![image](https://github.com/whoisdon/donkeyguide/assets/106766423/5759e9d2-7bec-4f2f-9467-b147d44694c6)

**Comment by whoisdon** [comment]
You can add a method to the `SlashCommands` class to prevent deep recursive calls. Within this method, you can handle and choose the objects you want to return from the class. Here's an example:

 ```js
toJSON() { const { client, botPermissions, userPermissions, ...data } = this; return data; }

**Comment by whoisdon** [comment]
You can add a method to the `SlashCommands` class to prevent deep recursive calls. Within this method, you can handle and choose the objects you want to return from the class. Here's an example:

 ```js
toJSON() {
   const { client, botPermissions, userPermissions, ...data } = this;
   return data; 
}
